root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server.exe ./cmd/server"
entrypoint = ["./tmp/server.exe"]
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "data"]
delay = 300
stop_on_error = true

[log]
time = true
